### PR TITLE
Epa wpa cleanup

### LINKED ISSUE #3: Issue with ep_after and EPA variables after failure to convert on 4th down
Hello!

I was working with the play-by-play data, and I think I ran across an issue with how the expected points variable is reported after a failure to convert on 4th down. The EPA came back as positive for almost all failed 4th down conversions, which seemed bizarre.

I have attached a screenshot that I think shows the problem. In the 4th row, Baylor goes for it on 4th down and fails to convert, losing 5 yards. I believe that the ep_after should be -3.756, the negative value of Oklahoma's ep_before on the next play. Instead, it is reported as 1.073, which I am guessing is equivalent to the EP if Baylor had a 1st and 10 from this new location.

cfbscrapr_problem

I hope that made sense, let me know if it doesn't or if you need more info!

### PR DESCRIPTION
**Pull request by saiemgilani**
# Summary of fixes, additions, deletions:
### 0) I renamed output columns to:
- give consistent conversion from camelCase to under_score. I missed several on the first pass through the package, hopefully the output will be consistent from here on out. I have changed the format of the `cfb_play_stat_player` function to give consistent columnar output with one row per `play_id`. 

### 2) Win Probability
* huge fix for win probability, the `scorediff` was being reported immediately and not at the pre-play level, causing incorrect WPA values. The WPA values should be significantly better aligned, please alert us if that is not the case.
* Defined new `score_diff` variables `score_diff_start` in WPA prep section

* switch to using CFBD API for offense_timeouts and defense_timeouts
* commenting out the `add_timeout` functions
* removing the `add betting columns` mapping
* removing the `wp_betting` mapping from the main function.

### 3) cfb_pbp_data function
Update assertions and calls:
- switch to similar url call to other functions in the package
- switch from self-calling `cfb_pbp_data` to pull in drives information, now uses the `cfb_drives` function from the package
- Moved penalty detection into its own function
   * Replace all case dependent regex with more concise code. Most changes occur in `penalty_detection` and `clean_pbp_dat`

- Following columns added to `clean_pbp_dat` function:
    * `scoring_play`
    * `pts_scored`
    * `td_play`
    * `touchdown`
    * `off_td_play`
    * `def_td_play`
    * `kickoff_play`
    * `kickoff_tb`
    * `kick_play`
    * `punt_play`
    * `punt`
    * `punt_tb`
    * `fumble_vec`
    * `rush_vec`
    * `pass_vec`
    * `sack_vec`
- added exports to all of these functions
### 4) Expected Points Added
* Fix Defensive 2 pt conversions
 * add lead_var for turnovers, 
 * define downs_turnover in the correct area
- rearrange turnover_vec condition (was not being triggered often enough) in the case_whens for the variables:
   * yardline
   * down
   * distance 
- Added to create_epa function:
   * first down by penalty, 
   * first down by yardage 
   * first play of drive flags.  
   * Add play counting columns for game, half, drive

- added  a better select statement at the end to make it more user friendly
### Create cfb_ratings_fpi.R  …
2516ef5
adapted from @sabinanalytics fork of the repo
### Create cfb_metrics_espn_wp.R …
9cb1f56
Graciously contributed by @mrcaseb

### Update cfb_play_stats_player.R …
remove -.data$secondsRemaining, appears to have been removed from API return
### Update cfb_betting_lines.R 
Logic was not catching all cases. Added column renaming
### Update cfb_game_team_stats.R 
Was not working properly for bye weeks

### Update: 
 - cfb_game_records.R, 
 - cfb_metrics_ppa_games.R, 
 - cfb_rankings.R , 
 - cfb_metrics_wp.R , 
 - cfb_metrics_wp_pregame.R,  
 - Update cfb_player_usage.R (rename id to athlete_id)
 - Update cfb_play_stats_player.R
- Update cfb_ratings_sp.R 
- Update cfb_ratings_sp_conference.R
- Update cfb_ratings_srs.R 
- cfb_play_stats_player.R
- cfb_recruiting_player.R 
- cfb_recruiting_position.R
- cfb_team_matchup.R
- Luckily, from now on, there are tests written for all of these functions.
Complete renaming of columns that were missed initially.
### Update cfb_game_media.R
conference name was supposed to be conference abbreviation. Assertion also changed correspondingly.

# Tests Added
### Mostly stubs of tests, but a solid start to check for columns matching expected
Create `test-cfb_betting_lines.R`
Create `test-cfb_conferences.R`
Create `test-cfb_drives.R`
Create `test-cfb_game_box_advanced.R`
Create `test-cfb_game_info.R`
Create `test-cfb_game_media.R`
Create `test-cfb_game_player_stats.R`
Create `test-cfb_game_records.R`
Create `test-cfb_game_team_stats.R`
Create `test-cfb_metrics_espn_wp.R`
Create `test-cfb_metrics_ppa_predicted.R`
Create `test-cfb_metrics_ppa_players_games.R`
Create `test-cfb_metrics_ppa_games.R`
Create `test-cfb_ratings_fpi.R`
Create `test-cfb_metrics_ppa_players_season.R`
Create `test-cfb_metrics_wp.R`
Create `test-cfb_metrics_wp_pregame.R`
Create `test-cfb_play_stats_player.R`
Create `test-cfb_team_matchup_records.R`
Create `test-cfb_coaches.R`
Create `test-cfb_play_stats_player.R`
Create `test-cfb_play_stats_types.R`
Create `test-cfb_play_types.R`
Create `test-cfb_player_info.R`
Create `test-cfb_player_returning.R`
Create `test-cfb_player_usage.R`
Create `test-cfb_rankings.R`
Create `test-cfb_ratings_sp.R`
Create `test-cfb_ratings_sp_conference.R`
Create `test-cfb_ratings_srs.R`
Create `test-cfb_recruiting_position.R`
Create `test-cfb_recruiting_team.R`
Create `test-cfb_stats_categories.R`
Create `test-cfb_recruiting_player.R`
Create `test-cfb_team_info.R`
Create `test-cfb_team_talent.R`
Create `test-cfb_venues.R`
Create `test-cfb_team_matchup.R`

### CODE REVIEW

File: R/create_epa.R [hunk 1]
```diff
@@ -155,199 +183,131 @@ create_epa <- function(clean_pbp_dat,
...
+  turnover_plays = which(pred_df$turnover == 1 & !kickoff_ind & (pred_df$play_type %in% turnover_play_type))
+  pred_df[turnover_plays, "ep_after"] = -1*pred_df[turnover_plays, "ep_after"]
+  
   # game end EP is 0
   pred_df[pred_df$end_half_game_end == 1, "ep_after"] = 0
 
   ## scoring plays from here on out
   pred_df[(pred_df$play_type %in% off_TD), "ep_after"] = 7
   pred_df[(pred_df$play_type %in% def_TD), "ep_after"] = -7
+  pred_df[pred_df$play_type == "Defensive 2pt Conversion", "ep_before"] = 1
```
Comment (meysubb) [inline R/create_epa.R:199]: Why are you setting the ep_before here as 1?

File: NEWS.md [hunk 2]
```diff
@@ -1,3 +1,14 @@
+# cfbscrapR 1.0.2
+- Fix issues with win probability added
+- Remove the `add betting columns()` and the current betting win probability model from the `cfb_pbp_data()` function
+- Fix downs turnovers and several other discrepancies in EPA computations
```
Comment (meysubb) [inline NEWS.md:4]: Is it possible to add the plot that Nate Manzo shared? If we can do a before/after I think itwould help here. It's a markdown so it should be possible to attach.

File: R/create_epa.R (hunk 1 above)
Comment (saiemgilani) [reply R/create_epa.R:199]: These are specific play_types with defensive 2pt conversion as the play_type, meaning they're separate from the touchdown play. I'm basically equating the expectation of a point after as 1 (could be like .96 or whatever). I am planning on adjusting for PATs shortly to give specific ep_afters based on whether the PAT was successful a couple lines up. I'm planning on getting to that this week

Comment (saiemgilani) [reply R/create_epa.R:199]: Oh wait, should I be setting it to zero and just not worry about that? I think that'd kinda fix it other than giving extra credit to the offense on those 6 prior-play touchdowns.

Comment (meysubb) [reply R/create_epa.R:199]: Yeah. I might lean towards the 0 solution. Because the pbp by doesn't separate out kickoffs. (This is something we can look to tackle more long term say in the off-season).

File: NEWS.md (hunk 2 above)
Comment (saiemgilani) [reply NEWS.md:4]: EPA_YardsGained_cfbscrapR
EPA_YardsGained_cfbscrapR2
new_version
test
WPA_YardsGained_cfbscrapR
WPA_YardsGained_cfbscrapR2
